---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install Ansible Lint
  - pip install -q ansible-lint

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Install required dependencies.
  - ansible-galaxy install danbohea.homebrew

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Role lint check
  - ansible-lint tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
