---

# https://docs.travis-ci.com/user/osx-ci-environment

matrix:
  include:
    # macOS 10.11
    - os: osx
      osx_image: xcode7.3
    # macOS 10.10
    - os: osx
      osx_image: xcode7.1
    # macOS 10.9
    - os: osx
      osx_image: beta-xcode6.2
  allow_failures:
    # macOS 10.10
    - osx_image: xcode7.1
    # macOS 10.9
    - osx_image: beta-xcode6.2
  fast_finish: true

install:
  # Debug info
  - python --version
  # Install pip
  - sudo easy_install pip
  # Install Ansible
  - sudo pip install ansible --quiet
  # Debug info
  - pip --version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  # Install required dependencies.
  - ansible-galaxy install danbohea.homebrew

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run test playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Idempotence test (run test playbook again & check output)
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
