---

# https://docs.travis-ci.com/user/osx-ci-environment

# Mac OS 10.11, 10.10 & 10.9
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: beta-xcode6.2
  allow_failures:
    - osx_image: xcode7.1
    - osx_image: beta-xcode6.2
  fast_finish: true

install:
  # Debug info
  - python --version
  # Update Homebrew
  - brew update
  # Install Python, separate from version that ships with OS X
  - brew install python
  #  Install Ansible
  - brew install ansible
  # Debug info
  - python --version
  - pip --version
  - ansible --version
  # Install Ansible Lint
  - sudo pip install -q ansible-lint
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  # Install required dependencies.
  - ansible-galaxy install danbohea.homebrew

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Lint
  - ansible-lint tests/test.yml

  # Run test playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Idempotence test (run test playbook again & check output)
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
