---

- name: Install Skype.
  homebrew_cask: name=skype state=present
  notify: brew cask cleanup

- name: Set default dialpad window visibility.
  osx_defaults:
    domain: com.skype.skype
    key: DialpadOpen
    type: bool
    value: "{{ skype_DialpadOpen }}"
  notify:
    - killall Skype

- name: Set default contacts view mode.
  osx_defaults:
    domain: com.skype.skype
    key: ContactListViewMode
    type: int
    value: "{{ skype_ContactListViewMode }}"
  notify:
    - killall Skype
